title: "TODO: Add a title"
description: "TODO: Add a description"
source: src
output: out
site-url: https://aedipamoss.github.io/notes
image: images/avatar.jpg
twitter: aedipamoss
assets:
  css:
    - style.css
  images:
    - bg.png
    - avatar.jpg
