version: 2.0

jobs:
  deploy:
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: go get github.com/aedipamoss/stationery
      - run: stationery
      - store_artifacts:
          path: out
          destination: site
      - run: ./.circleci/deploy-gh-pages.sh

workflows:
  version: 2
  ci:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
